printDebug: false
disableTabCompletion: false
simpleProjectileCheck: true
fireworks:
  mode: keep_item
  cooldown: 0 # Not implemented
  limit: 0 # Not implemented
arrows:
  mode: disabled
  cooldown: 0 # Not implemented
  limit: 0 # Not implemented