require_permission: true
arrow_damage_cooldown: true
firework_damage_cooldown: true
fire_configurations:
  example_machine_gun:
    consume_item: true
    fire_cooldown: 3
    max_charges: 20
    arrow:
      knockback: 2
      damage: 5.0
      pierce: 2
      critical: false