require_permission: false
fire_configurations:
  default:
    consume_item: true
    fire_cooldown: 2
    max_charges: 20
    arrow:
      knockback: 3
      damage: 10.0
      pierce: 3
      critical: true
  shotgun:
    fire_cooldown: 10
    max_charges: 3
    allow_projectile: arrow
    custom_firing:
      arrow_pickup: false
      pattern:
        type: line # point
        rotation: 90
      spread_x: 2
      spread_y: 20